#authentication used for the default user which connects to the remote Server.
#If another User should be Used, look into the servers.ini file
auth:
  user: root
  private_key: ~/.ssh/id_rsa
  public_key: ~/.ssh/id_rsa.pub
  sudo: 1
  key_auth: 1

# these packages must be installed in order to get all things working do not change these if you want to add packages, add them to your hostname.yml file
packages:
  - git
  - perl
  - zip
  - vim
  - unzip
  - sudo
  - curl
  - nginx
  - haveged
